config/routes.rb
Rails.application.routes.draw do
  resources :buyers
  root to: 'patients#all'
  get '/error', to: 'patients#error'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/buyer.rb
class Buyer < ApplicationRecord
end

app/models/patient.rb
class Patient < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/buyers_controller.rb
class BuyersController < ApplicationController
  before_action :set_buyer, only: [:show, :edit, :update, :destroy]

  # GET /buyers
  # GET /buyers.json
  def index
    @buyers = Buyer.all
  end

  # GET /buyers/1
  # GET /buyers/1.json
  def show
  end

  # GET /buyers/new
  def new
    @buyer = Buyer.new
  end

  # GET /buyers/1/edit
  def edit
  end

  # POST /buyers
  # POST /buyers.json
  def create
    @buyer = Buyer.new(buyer_params)

    respond_to do |format|
      if @buyer.save
        format.html { redirect_to @buyer, notice: 'Buyer was successfully created.' }
        format.json { render :show, status: :created, location: @buyer }
      else
        format.html { render :new }
        format.json { render json: @buyer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buyers/1
  # PATCH/PUT /buyers/1.json
  def update
    respond_to do |format|
      if @buyer.update(buyer_params)
        format.html { redirect_to @buyer, notice: 'Buyer was successfully updated.' }
        format.json { render :show, status: :ok, location: @buyer }
      else
        format.html { render :edit }
        format.json { render json: @buyer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buyers/1
  # DELETE /buyers/1.json
  def destroy
    @buyer.destroy
    respond_to do |format|
      format.html { redirect_to buyers_url, notice: 'Buyer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_buyer
      @buyer = Buyer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def buyer_params
      params.require(:buyer).permit(:name, :description, :age)
    end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  attr_reader :patients
  
  def all
    @patients = Patient.all
  end
  
  def error
    begin
      change = Service.new
      change.error_test(1)
      change.error_test(2)
    rescue => e
      flash[:status] = e
    end
  
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buyers_helper.rb
module BuyersHelper
end

app/views/buyers/_form.html.haml
= form_for @buyer do |f|
  - if @buyer.errors.any?
    #error_explanation
      %h2= "#{pluralize(@buyer.errors.count, "error")} prohibited this buyer from being saved:"
      %ul
        - @buyer.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :age
    = f.number_field :age
  .actions
    = f.submit 'Save'

app/views/buyers/edit.html.haml
%h1 Editing buyer

= render 'form'

= link_to 'Show', @buyer
\|
= link_to 'Back', buyers_path

app/views/buyers/index.html.haml
%h1 Listing buyers

%table
  %thead
    %tr
      %th Name
      %th Description
      %th Age
      %th
      %th
      %th

  %tbody
    - @buyers.each do |buyer|
      %tr
        %td= buyer.name
        %td= buyer.description
        %td= buyer.age
        %td= link_to 'Show', buyer
        %td= link_to 'Edit', edit_buyer_path(buyer)
        %td= link_to 'Destroy', buyer, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Buyer', new_buyer_path

app/views/buyers/new.html.haml
%h1 New buyer

= render 'form'

= link_to 'Back', buyers_path

app/views/buyers/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @buyer.name
%p
  %b Description:
  = @buyer.description
%p
  %b Age:
  = @buyer.age

= link_to 'Edit', edit_buyer_path(@buyer)
\|
= link_to 'Back', buyers_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Routing
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/patients/all.html.haml
%h3 All patients:
- change = Service.new
- @patients.each_with_index do |patient, index|
  = "#{index + 1}. "
  = change.uppercase(patient.name)
  = "-"
  = patient.description
  %br

app/views/patients/error.html.haml
- unless flash[:status].blank?
  %h1
    = flash[:status]